Zamir/van 1837/fix tpa skeleton
openedx/frontend-app-authn pull request #1189
Opened 2024-03-05 07:04 UTC by zainab-amir

### Description

There are two commits in this PR. 
1st commit is done to update the top margin for first appearance of skeleton loader. 
2nd commit is cherry picked from this OSPR: https://github.com/openedx/frontend-app-authn/pull/1086 

#### JIRA

[VAN-1837](https://2u-internal.atlassian.net/browse/VAN-1837)

#### How Has This Been Tested?

Locally

#### Screenshots/sandbox (optional):

|Before|After|
|-------|-----|
|<img width="281" alt="Screenshot 2024-03-05 at 10 25 35 AM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/aa704ed5-ffed-4767-b00a-b30e732c3c55"> |<img width="281" alt="Screenshot 2024-03-05 at 10 25 14 AM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/6ce1e154-c318-4fc9-a8b6-5039cad31269">|

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/2u-vanguards** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2024-03-05 15:22 UTC, arbrandes requested changes
Checking intended behavior.

2024-03-05 18:14 UTC, zainab-amir commented on src/common-components/ThirdPartyAuth.jsx
> +      {thirdPartyAuthApiStatus === PENDING_STATE || true ? (
This was my testing code and was accidentally merged. The latest code doesn't have it.

2024-03-06 10:56 UTC, syedsajjadkazmii approved these changes

2024-03-06 13:03 UTC, arbrandes approved these changes

2024-03-06 14:11 UTC, merged