fix: use paragon branding variables for colors
openedx/frontend-app-authn pull request #681
Opened 2022-11-21 21:36 UTC by shahbaz-arbisoft

We currently have branding issue in our repo. We are hardcoding branding colors in different parts of our code.
Now, we are using paragon branding variables instead of hardcoding the colors.

Tickets: https://2u-internal.atlassian.net/browse/VAN-1163

2022-11-22 16:17 UTC, arbrandes requested changes
This is awesome, thanks @shahbaz-arbisoft!  I only had one comment.

2022-11-22 16:17 UTC, arbrandes commented on src/sass/_style.scss
> +    background-color: white;
Do you mind using `$white` here and elsewhere?

2022-11-23 13:34 UTC, arbrandes approved these changes
Awesome, thanks!

2022-11-23 14:58 UTC, zainab-amir commented
Update: Waiting for UX to approve the color changes.

2022-11-28 14:57 UTC, merged