fix: change registration form for onramp
openedx/frontend-app-authn pull request #939
Opened 2023-06-12 11:05 UTC by ahtesham-quraish

Description:
In this we have changed the registration form on the basis of embed query param and hide the multiple things like registration button

How Has This Been Tested?
I have tested it locally.

Its related to: 
https://2u-internal.atlassian.net/browse/VAN-1476

Screenshots
<img width="703" alt="Screenshot 2023-06-12 at 4 03 25 PM" src="https://github.com/openedx/frontend-app-authn/assets/12580995/4490d1df-9ba6-4058-bc98-5f06aa6065e3">

2023-06-12 13:01 UTC, zainab-amir reviewed
Paragon classes should be used if needed

2023-06-12 13:24 UTC, ahtesham-quraish commented on src/data/constants.js
> +export const AUTH_PARAMS = ['course_id', 'enrollment_action', 'course_mode', 'email_opt_in', 'purchase_workflow', 'next', 'save_for_later', 'register_for_free', 'track', 'is_account_recovery', 'embed
resolved

2023-06-13 09:41 UTC, zainab-amir requested changes

2023-06-13 09:41 UTC, zainab-amir commented on src/logistration/Logistration.jsx
> +  const renderForm = () => (
```suggestion
  const renderLogistrationTabs = () => (
```

2023-06-13 09:41 UTC, zainab-amir commented on src/logistration/Logistration.jsx
> +              : (!variant && !isValidTpaHint() && (
```suggestion
              : (!isRegistrationEmbedded && !isValidTpaHint() && (
```

2023-06-13 09:41 UTC, zainab-amir commented on src/logistration/Logistration.jsx
> +                { 'main-content-background': variant },
This class needs to be removed.

2023-06-13 09:41 UTC, zainab-amir commented on src/logistration/Logistration.jsx
>    );
```suggestion
  return (
    isRegistrationEmbedded ? (
      renderForm()
    ) : (
      <BaseComponent>
        {renderForm()}
      </BaseComponent>
    )
  );
```

2023-06-13 09:41 UTC, zainab-amir commented on src/logistration/Logistration.jsx
> +  const { variant } = getAllPossibleQueryParams();
```suggestion
  const isRegistrationEmbedded = getAllPossibleQueryParams()?.variant === 'embedded' && selectedPage === REGISTER_PAGE;
```

2023-06-13 09:41 UTC, zainab-amir commented on src/register/RegistrationPage.jsx
> +  const { variant } = queryParams;
Similar approach can be used as above. 
```suggestion
  const isRegistrationEmbedded = queryParams?.variant === 'embedded';
```

2023-06-13 09:41 UTC, zainab-amir commented on src/register/RegistrationPage.jsx
> +              { 'form--centerd': variant },
We can use paragon classes for this
```suggestion
              { 'w-100 m-auto': isRegistrationEmbedded },
```

2023-06-13 09:41 UTC, zainab-amir commented on src/register/RegistrationPage.jsx
> +              {!variant && (
```suggestion
              {!isRegistrationEmbedded && (
```

2023-06-13 10:27 UTC, zainab-amir approved these changes

2023-06-13 11:10 UTC, merged